### ISSUE TITLE
Add support for user CAS url

### ISSUE THREAD

**Issue by matthewvalimaki** [IUCrimson/AspNet.Security.CAS#1]
As of now implementation allows only one url: `CasServerUrlBase`. This is used by ticket validators and  user redirect. A use case exists where user is taken to a different domain than what the server side uses.

**Comment by blakepell** [comment]
To clarify, are you saying you want to invoke CAS and then have it redirect to another domain after authentication (as opposed to where you came from)?

**Comment by matthewvalimaki** [comment]
@blakepell no I did not mean that. Say browser goes to `cas.server.com` and as it is today ticket verification would go to the same url. I'm proposing adding a 2nd url which, for non-browser "internal", ticket verification would go to `cas.service.server.com`.
