### ISSUE TITLE
Combining with Authorization

### ISSUE THREAD

**Issue by AndyPootsQUB** [IUCrimson/AspNet.Security.CAS#10]
Hi - would you have a code sample/walkthrough of how to combine this with ASP.NET Core aspnet security to allow for traditional authorisation on controllers - so that I could write code like:

**[Authorize(Roles = "System Administrator")]**

in my controllers?

Any help much appreciated.

**Comment by davidmdem** [comment]
There are two ways you could go about adding role information after a successful CAS authentication.  Personally, I have used both approaches to add user roles based on LDAP or database queries.

### Claims Transformation 

You can write a custom transformer based on the [`IClaimsTransformation`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.iclaimstransformation?view=aspnetcore-2.0) interface.  It will be called after
any successful `AuthenticateAsync` call.

```c#
// Define a custom claims transformer.
private class ClaimsTransformer : IClaimsTransformation 
{
    // Can consume services from DI as needed, including scoped DbContexts
    public ClaimsTransformer(IHttpContextAccessor httpAccessor) { }
    public Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal p) 
    {
        p.AddIdentity(new ClaimsIdentity());
        return Task.FromResult(p);
    }
}

// Register your the ClaimsTransformer in Startup.cs
services.AddSingleton<IClaimsTransformation, ClaimsTransformer>();
```

### Cookie Events

The `CookieAuthenticationOptions` object configured in `AddCookie` has an `Events` property where you can assign a callback for `SignedIn`.  This is less convenient from a DI standpoint, but depending on your needs and configuration might have less of a footprint.

I've added the following example in the sample project for setting roles during the Cookie middleware's `OnSigningIn` event.

```c#
o.Events = new CookieAuthenticationEvents
{
    // Add user roles to the existing identity.  
    // This example is giving every user "User" and "Admin" roles.
    // You can use services or other logic here to determine actual roles for your users.
    OnSigningIn = context =>
    {
        // Use `GetRequiredService` if you have a service that is using DI or an EF Context.
        // var username = context.Principal.Identity.Name;
        // var userSvc = context.HttpContext.RequestServices.GetRequiredService<UserService>();
        // var roles = userSvc.GetRoles(username);
        
        // Hard coded roles.
        var roles = new[] { "User", "Admin" };

        // `AddClaim` is not available directly from `context.Principal.Identity`.
        // We can add a new empty identity with the roles we want to the principal. 
        var identity = new ClaimsIdentity();
        
        foreach (var role in roles)
        {
            identity.AddClaim(new Claim(ClaimTypes.Role, role));
        }

        context.Principal.AddIdentity(identity);

        return Task.FromResult(0);
    }
};
```

**Comment by davidmdem** [comment]
I'll add that while I've used both, `OnSigningIn` is probably preferable for adding roles since it will only fire when they login.  The claims transformation runs on every authentication request, so there might be some extra work required if you're not wanting to recalculate/fetch the roles on every single authenticated request.
