### ISSUE TITLE
Custom Service URL

### ISSUE THREAD

**Issue by NickDelBen** [IUCrimson/AspNet.Security.CAS#16]
Is there a way to customize what goes in the "service" GET param on the initial request to the CAS server.

My asp.net core app lives inside a container, and the service seems to always be the container name, instead of my server fqdn.

**Comment by davidmdem** [comment]
No, not directly.  The return URL that goes into `service` parameter [is built here](https://github.com/IUCrimson/AspNet.Security.CAS/blob/master/src/AspNetCore.Security.CAS/CasHandler.cs#L94) and uses `Request.Host` for the domain.

I checked around some of the MVC code in [places where Microsoft is constructing URLs](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/RequireHttpsAttribute.cs#L80).  Aside from me not using `ToUriComponent` (which I'll add now that I see it's a thing), it's pretty much the same `Request.Host` parameter.  

I'm curious - what does `HttpContext.Request.Host` return if you call look at it in one of your actions/controllers?

With all of that said, I don't think it would be a problem to allow for a configuration option to force a specific domain name in that spot.  Would this option only replace `Request.Host` or would it also cover [`Request.PathBase`](https://github.com/IUCrimson/AspNet.Security.CAS/blob/master/src/AspNetCore.Security.CAS/CasHandler.cs#L95) as well?

**Comment by NickDelBen** [comment]
**I'm curious - what does HttpContext.Request.Host return if you call look at it in one of your actions/controllers?**

For me this returns the proper hostname (what i want), however the host in the url is still containerhostname:port. I have fixed this in my fork to pull the service name from an injected IConfiguration Service.

**With all of that said, I don't think it would be a problem to allow for a configuration option to force a specific domain name in that spot. Would this option only replace Request.Host or would it also cover Request.PathBase as well?**

In my fork I replace the entire "service" GET parameter with the value from the injected Configuration Service.

**Comment by davidmdem** [comment]
Closing to merge conversation into #17.  Feel free to reopen if you feel like these are really two separate discussions.
