### ISSUE TITLE
What to do with ticket?

### ISSUE THREAD

**Issue by NickDelBen** [IUCrimson/AspNet.Security.CAS#17]
Maybe I am missing something here in the flow.

1. User hits my defined login URL.
2. This redirects them to the CAS server.
3. After logging in user is redirected back to my page with the ?ticket=<...> get parameter appended.

At this point User.Identity reports authenticated: false
Should there be another endpoint to exchange the ticket for data, or am i missing a configuration option that would yield the user already being authenticated at this point.

**Comment by davidmdem** [comment]
I'm still responding to #16, but I think this has to do with the way your fork is replacing the `service` parameter.  

> In my fork I replace the entire "service" GET parameter with the value from the injected Configuration Service.

Are you still [appending state](https://github.com/IUCrimson/AspNet.Security.CAS/blob/master/src/AspNetCore.Security.CAS/CasHandler.cs#L96)?

Edit: Providing the `Options.CallbackPath` is important also.  

Overall, I would suggest that you only override the domain name that wasn't translating well from within your container instead of the entire `service` parameter.

**Comment by NickDelBen** [comment]
The problem appears to be with GET URI string decoding and intrepretation on some CAS servers. 

Here inside the `BuildReturnTo` function there is a `Uri.EscapeDataString`
```c#
private string BuildReturnTo(string state)
{
    return Request.Scheme + "://" + Request.Host +
           Request.PathBase + Options.CallbackPath +
           "?state=" + Uri.EscapeDataString(state);
}
```

Which is used here inside the `HandleRemoteAuthenticateAsync` function
```c#
var casService = Uri.EscapeDataString(BuildReturnTo(state));
var authTicket = await Options.TicketValidator.ValidateTicket(Context, properties, Scheme, Options, casTicket, casService);
```

This results in a URI that looks like `<CAS_SERVER_LOGIN_URL>?service=<SERVICE_URL>&signin-cas?state=<ENCODED_STATE>`

For example it could look like `cas.example.com/login?service=https://myapp.com/landing&signin-cas?state=SDAF6SDFG...`

We can see that there are two `?` which signals the beginning of the GET parameters. Allthough the `state` passed in to `BuildReturnTo` is encoded, and then encoded again inside `HandleRemoteAuthenticateAsync()` I doubt the second call would modify the already encoded `state` data. 

The concern is how the server will interpret the fact that the GET parameters do not start with `?` and then append a `&` for any additional parameters.

That is too say a well formed URI would look like this:
    example.com **?** key1=val1  **&** key2=val2 **&** key3=val3)

However the URI built looks like this
    example.com **?** key1=val1 **&** key2=val2 **?** key3=val3)

**Comment by davidmdem** [comment]
>This results in a URI that looks like `<CAS_SERVER_LOGIN_URL>?service=<SERVICE_URL>&signin-cas?state=<ENCODED_STATE>`

That's not quite true.  The resulting URL for `casService` used in the ticket validation phase looks like this (running on `localhost`):
`http%3A%2F%2Flocalhost%3A58886%2Fsignin-cas%3Fstate%3DCfDJ8OS...`

`EscapeDataString` will escape the 2nd `?` for the ticket validating URL.

I won't have time today, but tomorrow I'll implement a 2.0.3 version that will allow you to manually specify the FDQN in the `CasOptions`.  

If you'd like to continue pressing down this road, I wonder if you could upload your fork or grant me access?  I only did a quick look, but I couldn't find your fork to look at.  I'm still pretty sure replacing the `service` param outright is the cause of this problem (unless you're saying you can reproduce this with the default code/sample project).

**Comment by NickDelBen** [comment]
Ill have to check when i'm back at work tomorrow and can access the CAS server.

It is possible I misunderstand the flow. Is the controller endpoint the CAS server returns the client to after logging in supposed to be the same controller (login) endpoint that redirected them there in the first place?

I simply cloned the repo for the fork. If I do figure out anything tomorrow I will submit a pull request for you to look at.

**Comment by davidmdem** [comment]
Added a [dev/2.0.3 branch](https://github.com/IUCrimson/AspNet.Security.CAS/tree/dev/2.0.3) that adds a `ServiceHost` option.  This should let you specify the FDQN used when constructing the `service` param.  

```
.AddCAS(o =>
{
    o.CasServerUrlBase = Configuration["CasBaseUrl"];   // Set in `appsettings.json` file.
    o.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    o.ServiceHost = "www.mydomain.com";
});
```

It's a pretty small addition and could help others in a similar situation, so I'm curious if it can solve the issue you describe in #16, even if you don't end up using this option as a solution.

**Comment by NickDelBen** [comment]
This does work and adequately resolves the problem I was having.

Another resolution to the problem was to change the request Host header value before it hit ASP.net (IE in my reverse proxy).

This problem leads to another, however. For the same reason request.Host was giving the container name before, Request.Scheme is giving http.

Even though requests to the reverse proxy are all https, the proxy sends another http request back to the container in the middle. 

I will submit a pull request to the dev branch using the same pattern to allow configurable http scheme as well.

**Comment by NickDelBen** [comment]
Pull request is sent. I believe this resolves any issue I was having at this point.

Hopefully these changes will be reflected in the NuGet package soon.
