### ISSUE TITLE
How to get user attribute from CAS Like email and other in .NetCore

### ISSUE THREAD

**Issue by amitsaxucsb** [IUCrimson/AspNet.Security.CAS#28]
Hi i am using CAS for single sign-on in my application(.Net Core2.2). I was able to login with CAS, I am getting the username only but not email or any other attributes from CAS.

For authentication in CAS side I am using AspNetCore.Security.CAS Nuget Pacakage and configured in Startup.cs file below is the code.

In startup's ConfigureServices method:

services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)

.AddCookie(options => {
    options.LoginPath = new PathString("/login");
})

.AddCAS(options =>
{
    options.CasServerUrlBase = Configuration["CasBaseUrl"];   
    options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
});
In your startup's Configure method before UseMvc:

app.UseAuthentication();
In Context I am able to get username from context.Principal.Identity.Name but not able to find out other attribute information. Please help me for this.

**Comment by dbbarret** [comment]
That is all CAS should return.  Now that _username_ is authenticated, you should then be able to lookup _username_ in some other system (LDAP, homegrown, whatever) to get more info about the user and/or to see what they are authorized to do.

**Comment by amitsaxucsb** [comment]
> That is all CAS should return. Now that _username_ is authenticated, you should then be able to lookup _username_ in some other system (LDAP, homegrown, whatever) to get more info about the user and/or to see what they are authorized to do.
@dbbarret  Thank you for quick Response but When I get the Service ticket from cas and resend this ticket to cas servicevalidate url then in postman it gives me whole XML but in case of AspNetCore.Security.CAS package which i am using in my app then it gives me only username not other attribute. Please help me in this situation. I have alredy checked the context property but not able to get the attribute detail...
In Postaman call I get:
<cas:serviceResponse xmlns:cas="http://www.yale.edu/tp/cas">
  <cas:authenticationSuccess>
    <cas:user>amitsaxena</cas:user>
    <cas:attributes>
      <cas:isFromNewLogin>true</cas:isFromNewLogin>
      <cas:mail>amitsaxena@gmail.com</cas:mail>
      <cas:authenticationDate>Wed Oct 23 11:09:43 PDT 2019</cas:authenticationDate>
      <cas:displayName>Saxena, Amit</cas:displayName>
      <cas:givenName>Amit</cas:givenName>
      <cas:ID>83B62345-4FFF-11E9-B468-AC1CE068EA70</cas:ID>
      <cas:cn>Amit Saxena</cas:cn>
      <cas:uid>amitsaxena</cas:uid>
      <cas:sn>Saxena</cas:sn>
    </cas:attributes>
  </cas:authenticationSuccess>
</cas:serviceResponse>

In My .Net Core Startup.cs
services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
               .AddCookie(o =>
               {
                   o.LoginPath = new PathString("/login");

                   o.AccessDeniedPath = new PathString("/access-denied");
                  
                   o.Cookie = new CookieBuilder
                   {
                       Name = ".AspNetCore.CasiEval"
                       
                   };

                   o.Events = new CookieAuthenticationEvents
                   {
                       
                        // Add user roles to the existing identity.  
                        // This example is giving every user "User" and "Admin" roles.
                        // You can use services or other logic here to determine actual roles for your users.
                       OnSigningIn = async context =>
                       {
                           
                           string baseUrl = string.Empty;
                           var username = context.Principal.Identity.Name;
                           var userSvc = context.HttpContext.RequestServices.GetRequiredService<iUserService>();
                           var ticket_val = context.HttpContext.Request.Query["ticket"].ToString(); 
                           var state_val= context.HttpContext.Request.Query["state"].ToString();

                           
                           await Task.Delay(100);
                           return;// Task.FromResult(0);
                        }
                   };
               })
               .AddCAS(o =>
               {
                   o.CasServerUrlBase = Configuration["CasBaseUrl"];   // Set in `appsettings.json` file.
                   o.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                   o.SaveTokens = true;
                   o.CallbackPath = new PathString("/Home/Index");
                   //o.AttributesParent=
                   //o.EscapeServiceString = false;
               });

Please suggest me how can i get other detail or XML data which i require from CAS . Is there any property which i have to set or may be i have to do another things...Please advice me it will really help me to find out the things...
