### ISSUE TITLE
Sub Route Environment

### ISSUE THREAD

**Issue by hampton1122** [IUCrimson/AspNet.Security.CAS#6]
We are running this on a subroute with an Angular frontend. The AddCookie options.LoginPath needs to go to /account/login but it is not honoring that.
```cs 
services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
              .AddCookie(options =>
              {
                  options.LoginPath = new PathString("/account/login");
              })
              .AddCAS(options =>
              {
                  options.CasServerUrlBase = Configuration["CasBaseUrl"];   // Set in `appsettings.json` file.
                  options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                  options.CallbackPath = new PathString("/account/signin-cas");
              });
```
User Controller Route
```cs 
[AllowAnonymous]
        [Route("account/login")]
        public async Task Login(string returnUrl)
        {
            var props = new AuthenticationProperties { RedirectUri = returnUrl };
            await HttpContext.ChallengeAsync("CAS", props);
        }
```

It appears to be sending to the root /login. Are we missing something? @davidmdem

**Comment by davidmdem** [comment]
I can't see anything in the setup you provided that would explain the cookie middleware failing to send you to the `account/login` route.

To help test and maybe find some differences in your setup, I've changed the [CookieSample](https://github.com/IUCrimson/AspNet.Security.CAS/tree/test/issue-6/samples/CookieSample) project to match the configuration you have above.  These changes can be found in a new [test/issue-6](https://github.com/IUCrimson/AspNet.Security.CAS/tree/test/issue-6) branch of this repository.

Are you able to clone this repo and successfully navigate the authenticated page in the CookieSample app?

**Comment by davidmdem** [comment]
Going to close this issue since I can not reproduce the behavior being asked about.  Feel free to reopen if you find that this is a consistent issue or if you can reproduce the behavior using the sample project.
