### ISSUE TITLE
Logout and validate ticket

### ISSUE THREAD

**Issue by mspasiuk** [IUCrimson/AspNet.Security.CAS#7]
Hi,
I'm trying this library in my api project with net core 2.

I was able to succesfully login (being redirected to CAS page and the back to my app)
I have two questions?

1. If I logout in CAS from another application (2) in my app, it seems that my login is still valid, How can I check if my ticket is still valid?
2. What about the logout action? Is ok something like

```
[Route("logout")]
public async Task Logout(string returnUrl) {
            var props = new AuthenticationProperties { RedirectUri = returnUrl };
            var user = HttpContext.User.Identity;
            await HttpContext.SignOutAsync();
}
```

**Comment by davidmdem** [comment]
Hi and thanks for your questions. 

1.  This would make sense if that other application is just signing out of itself and not also signing the user out of CAS by sending them to `https://<your.cas.server>/logout`.  CAS itself maintains an authentication cookie for the user's current session.  If yours or another app sends them back to CAS login page again during their session, they will not be prompted to login again causing your application's back and forth with CAS to happen imperceptibly fast.

  The CAS exchange for you application is happening though.  You can verify this in a few places.  
  - Put a breakpoint in the `login` method to see that the cookie middleware is challenging them after they've logged out.
  - Use your browsers debug tool to verify that the authentication cookie has been deleted.
  - Using the browser tools, you can also check the value of your authentication cookie to see that even though you don't get CAS prompted again, your site is going through the motions and issuing a new cookie with a different encrypted value.

2.  I've added the [following example](https://github.com/IUCrimson/AspNet.Security.CAS/blob/master/samples/CookieSample/Controllers/HomeController.cs#L54) to the sample project where I try to explain the behavior:

```C#
        /// <summary>
        /// Removes authentication cookie and redirects back to the home page.
        /// </summary>
        [HttpGet("logout")]
        public async Task<IActionResult> Logout()
        {
            // Removes the user's auth cookie for this site and domain. 
            await HttpContext.SignOutAsync();

            // Do a full CAS logout.  
            // This removes the user's CAS auth cookie from the CAS domain.
            return Redirect($"{_configuration["CasBaseUrl"]}/logout");

            // Send them back to the home page.  
            // The user will remain signed into CAS. This means that if they again 
            // click to `AuthorizedPage`, they would be sent to `login` and challenged,
            // but the CAS login would be transparent/instant.
            //return RedirectToAction("Index");
        }
```

**Comment by mspasiuk** [comment]
Thanks! I understand now
